apiVersion: skaffold/v2beta21
kind: Config
build:
  artifacts:
    - image: springcloudservices/adoption-operator
      custom:
        buildCommand: |
          ./gradlew :with-kubernetes-java-client:bootBuildImage \
          --imageName="$IMAGE" --builder="gcr.io/paketo-buildpacks/builder:base"
        dependencies:
          paths:
            - with-kubernetes-java-client/src/main/**
            - with-kubernetes-java-client/build.gradle.kts
            - build.gradle.kts
    - image: springcloudservices/adoption-center
      context: adoption-center
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        dependencies:
          paths:
            - src/main/**
            - build.gradle.kts
deploy:
  kubectl:
    manifests:
      - ./crds/custom-resource-definition.yaml
    flags:
      apply:
        - --force
  kustomize:
    paths:
      - manifests
profiles:
  - name: with-java-operator-sdk
    patches:
      - op: replace
        path: /build/artifacts/0/context
        value: with-java-operator-sdk
