apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adoption-operator
commonLabels:
  app.kubernetes.io/part-of: adoption-operator

resources:
  - operator-namespace.yaml
  - operator-deployment.yaml
  - operator-resources-cluster-role.yaml
  - operator-resources-cluster-role-binding.yaml
  - operator-resources-namespaced-role.yaml
  - operator-resources-namespaced-role-binding.yaml
  - operator-service-account.yaml
