apiVersion: apps/v1
kind: Deployment
metadata:
  name: adoption-operator
spec:
  selector:
    matchLabels:
      app: adoption-operator
  template:
    metadata:
      labels:
        app: adoption-operator
    spec:
      serviceAccountName: adoption-operator
      containers:
        - name: adoption-operator
          image: springcloudservices/adoption-operator
          env:
            - name: LOGGING_LEVEL_COM_EXAMPLE_OPERATOR
              value: debug
            - name: ADOPTION_CENTER_IMAGE
              value: springcloudservices/adoption-center:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
