apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-operator-resources-role-binding
  namespace: adoption-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sample-operator-resources-role
subjects:
- kind: ServiceAccount
  name: adoption-operator
