apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-operator-resources-cluster-role
rules:
  - apiGroups:
      - operator.example.com
    resources:
      - catsforadoption
      - adoptioncenters
    verbs:
      - get
      - list
      - watch
      - patch

  - apiGroups:
      - operator.example.com
    resources:
      - catsforadoption/status
    verbs:
      - patch

  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
