apiVersion: "operator.example.com/v1alpha1"
kind: CatForAdoption
metadata:
  name: my-precious-fluffy-ball
spec:
  name: Chocobo
  dateOfBirth: 2014-09-17
  description: She is chubby, lazy, but always polite. She does not need much attention from you, but when she does, there is no way you can resist petting her.
  adoptionCenterName: kittens-dream-land
