apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pingservices.sample.operator.java
spec:
  group: sample.operator.java
  scope: Namespaced
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
        scale:
          specReplicasPath: .spec.count
          statusReplicasPath: .status.replicas
      additionalPrinterColumns:
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                count:
                  type: integer
                  exclusiveMinimum: false
                path:
                  type: string
                  description: The path to ping the service with
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The unique identifier of a condition, used to distinguish between other conditions in the resource.
                      status:
                        type: string
                        description: The status of the condition, either True, False or Unknown.
                      lastTransitionTime:
                        type: string
                        description: Last time the condition of a type changed from one status to another. The required format is 'yyyy-MM-ddTHH:mm:ssZ', in the UTC time zone.
                      reason:
                        type: string
                        description: The reason for the condition's last transition (a single word in CamelCase).
                  description: List of status conditions.
  names:
    plural: pingservices
    singular: pingservice
    kind: PingService
    shortNames:
      - ping
      - pings
