apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: adoptioncenters.operator.example.com
spec:
  group: operator.example.com
  scope: Cluster
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  names:
    plural: adoptioncenters
    singular: adoptioncenter
    kind: AdoptionCenter
    shortNames:
      - ac
      - acs
